# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image as the base image
FROM node:14-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the application
RUN npm run build

# Use a separate runtime environment
FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy only the build output and node_modules from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Copy the .env.example file and rename it to .env, this should be overridden with real values at runtime
COPY .env.example .env

# Expose the port the app runs on
# (This line is optional and depends on whether you want to specify a port to be exposed)

# Command to run the application
CMD ["node", "build/index.js"]